### ISSUE TITLE
Error message when opening Crucible tab when you haven't played any Crucible games

### ISSUE THREAD

**Issue by cg5-** [SarKurd/Destiny-Report#79]
I've never played a Crucible game, and when I open the Crucible tab I get an error message. In the JS console I get `TypeError: Cannot read property 'overallCrucible' of undefined`.

**Comment by SarKurd** [comment]
Thanks for the report.
Could you please give me your gamertag and platform so i can test it? finding a player who hasn't played crucible is a little difficult.

You can send me a private message on twitter if you don't want to share it here.

**Comment by cg5-** [comment]
jeff#11818, PC
